{% set data= load_setup_py_data() %}
package: 
  name: ts-integrationtests
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: generic
  script: python -m pip install --ignore-installed .
  entry_points:
    - auxtel_disabled_enabled = lsst.ts.IntegrationTests.auxtel_disabled_enabled:run_auxtel_disabled_enabled
    - auxtel_housekeeping = lsst.ts.IntegrationTests.auxtel_housekeeping:run_auxtel_housekeeping
    - auxtel_image_taking = lsst.ts.IntegrationTests.image_taking_verification:run_auxtel_image_taking
    - auxtel_latiss_acquire_and_take_sequence = lsst.ts.IntegrationTests.auxtel_latiss_acquire_and_take_sequence:run_auxtel_latiss_acquire_and_take_sequence
    - auxtel_latiss_calibrations = lsst.ts.IntegrationTests.auxtel_latiss_calibrations:run_auxtel_latiss_calibrations
    - auxtel_latiss_cwfs_align = lsst.ts.IntegrationTests.auxtel_latiss_cwfs_align:run_auxtel_latiss_cwfs_align
    - auxtel_offline_standby = lsst.ts.IntegrationTests.auxtel_offline_standby:run_auxtel_offline_standby
    - auxtel_prepare_for_flat = lsst.ts.IntegrationTests.auxtel_prepare_for_flat:run_auxtel_prepare_for_flat
    - auxtel_prepare_for_onsky = lsst.ts.IntegrationTests.auxtel_prepare_for_onsky:run_auxtel_prepare_for_onsky
    - auxtel_shutdown = lsst.ts.IntegrationTests.auxtel_shutdown:run_auxtel_shutdown
    - auxtel_standby_disabled = lsst.ts.IntegrationTests.auxtel_standby_disabled:run_auxtel_standby_disabled
    - auxtel_stop = lsst.ts.IntegrationTests.auxtel_stop:run_auxtel_stop
    - auxtel_track_target = lsst.ts.IntegrationTests.auxtel_track_target:run_auxtel_track_target
    - auxtel_visit = lsst.ts.IntegrationTests.auxtel_visit:run_auxtel_visit
    - comcam_calibrations = lsst.ts.IntegrationTests.comcam_calibrations:run_comcam_calibrations
    - comcam_image_taking = lsst.ts.IntegrationTests.image_taking_verification:run_comcam_image_taking
    - eas_disabled_enabled = lsst.ts.IntegrationTests.eas_disabled_enabled:run_eas_disabled_enabled
    - eas_standby_disabled = lsst.ts.IntegrationTests.eas_standby_disabled:run_eas_standby_disabled
    - enabled_offline = lsst.ts.IntegrationTests.enabled_offline:run_enabled_offline
    - maintel_disabled_enabled = lsst.ts.IntegrationTests.maintel_disabled_enabled:run_maintel_disabled_enabled
    - maintel_housekeeping = lsst.ts.IntegrationTests.maintel_housekeeping:run_maintel_housekeeping
    - maintel_offline_standby = lsst.ts.IntegrationTests.maintel_offline_standby:run_maintel_offline_standby
    - maintel_standby_disabled = lsst.ts.IntegrationTests.maintel_standby_disabled:run_maintel_standby_disabled
    - obssys2_disabled_enabled = lsst.ts.IntegrationTests.obssys2_disabled_enabled:run_obssys2_disabled_enabled
    - obssys2_standby_disabled = lsst.ts.IntegrationTests.obssys2_standby_disabled:run_obssys2_standby_disabled
    - load_camera_playlist = lsst.ts.IntegrationTests.load_camera_playlist:load_camera_playlist

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-salobj
    - ts-idl
    - yamllint
    - parameterized
  source_files:
    - python
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python

about:
  home: https://github.com/lsst-ts/ts_IntegrationTests
