{% set data= load_setup_py_data() %}
package: 
  name: ts-integrationtests
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --ignore-installed .
  entry_points:
    - auxtel_disabled_enabled = lsst.ts.IntegrationTests.auxtel_disabled_enabled:run_auxtel_disabled_enabled
    - auxtel_enable_atcs = lsst.ts.IntegrationTests.auxtel_enable_atcs:run_auxtel_enable_atcs
    - auxtel_housekeeping = lsst.ts.IntegrationTests.auxtel_housekeeping:run_auxtel_housekeeping
    - auxtel_image_taking = lsst.ts.IntegrationTests.image_taking_verification:run_auxtel_image_taking
    - auxtel_latiss_acquire_and_take_sequence = lsst.ts.IntegrationTests.auxtel_latiss_acquire_and_take_sequence:run_auxtel_latiss_acquire_and_take_sequence
    - auxtel_latiss_calibrations = lsst.ts.IntegrationTests.auxtel_latiss_calibrations:run_auxtel_latiss_calibrations
    - auxtel_latiss_cwfs_align = lsst.ts.IntegrationTests.auxtel_latiss_cwfs_align:run_auxtel_latiss_cwfs_align
    - auxtel_offline_standby = lsst.ts.IntegrationTests.auxtel_offline_standby:run_auxtel_offline_standby
    - auxtel_prepare_for_flat = lsst.ts.IntegrationTests.auxtel_prepare_for_flat:run_auxtel_prepare_for_flat
    - auxtel_prepare_for_onsky = lsst.ts.IntegrationTests.auxtel_prepare_for_onsky:run_auxtel_prepare_for_onsky
    - auxtel_reset_offsets = lsst.ts.IntegrationTests.auxtel_reset_offsets:run_auxtel_reset_offsets
    - auxtel_shutdown = lsst.ts.IntegrationTests.auxtel_shutdown:run_auxtel_shutdown
    - auxtel_standby_disabled = lsst.ts.IntegrationTests.auxtel_standby_disabled:run_auxtel_standby_disabled
    - auxtel_stop = lsst.ts.IntegrationTests.auxtel_stop:run_auxtel_stop
    - auxtel_track_target = lsst.ts.IntegrationTests.auxtel_track_target:run_auxtel_track_target
    - auxtel_visit = lsst.ts.IntegrationTests.auxtel_visit:run_auxtel_visit
    - comcam_calibrations = lsst.ts.IntegrationTests.comcam_calibrations:run_comcam_calibrations
    - comcam_image_taking = lsst.ts.IntegrationTests.image_taking_verification:run_comcam_image_taking
    - eas_disabled_enabled = lsst.ts.IntegrationTests.eas_disabled_enabled:run_eas_disabled_enabled
    - eas_standby_disabled = lsst.ts.IntegrationTests.eas_standby_disabled:run_eas_standby_disabled
    - gencam_disabled_enabled = lsst.ts.IntegrationTests.gencam_disabled_enabled:run_gencam_disabled_enabled
    - gencam_standby_disabled = lsst.ts.IntegrationTests.gencam_standby_disabled:run_gencam_standby_disabled
    - enabled_offline = lsst.ts.IntegrationTests.enabled_offline:run_enabled_offline
    - lsstcam_calibrations = lsst.ts.IntegrationTests.lsstcam_calibrations:run_lsstcam_calibrations
    - lsstcam_image_taking = lsst.ts.IntegrationTests.image_taking_verification:run_lsstcam_image_taking
    - maintel_disabled_enabled = lsst.ts.IntegrationTests.maintel_disabled_enabled:run_maintel_disabled_enabled
    - maintel_housekeeping = lsst.ts.IntegrationTests.maintel_housekeeping:run_maintel_housekeeping
    - maintel_standby_disabled = lsst.ts.IntegrationTests.maintel_standby_disabled:run_maintel_standby_disabled
    - obssys_disabled_enabled = lsst.ts.IntegrationTests.obssys_disabled_enabled:run_obssys_disabled_enabled
    - obssys_standby_disabled = lsst.ts.IntegrationTests.obssys_standby_disabled:run_obssys_standby_disabled
    - csc_state_transition = lsst.ts.IntegrationTests.csc_state_transition:csc_state_transition
    - load_camera_playlist = lsst.ts.IntegrationTests.load_camera_playlist:load_camera_playlist
    - love_stress_test = lsst.ts.IntegrationTests.love_stress_test:run_love_stress_test

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-salobj
    - ts-idl
    - yamllint
    - parameterized
  source_files:
    - python
    - tests
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - ts-salobj
    - ts-idl

about:
  home: https://github.com/lsst-ts/ts_IntegrationTests
