{% set data= load_setup_py_data() %}
package: 
  name: "ts-integrationtests"
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed -r tests/requirements.txt .

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-salobj
    - ts-idl
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - yamllint

about:
  home: "https://github.com/lsst-ts/ts_IntegrationTests"

