{% set data= load_setup_py_data() %}
package: 
  name: ts-integrationtests
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: generic
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - auxtel_disabled_enabled = lsst.ts.IntegrationTests.auxtel_disabled_enabled:run_auxtel_disabled_enabled
    - auxtel_offline_standby = lsst.ts.IntegrationTests.auxtel_offline_standby:run_auxtel_offline_standby
    - auxtel_prepare_for_flatfield = lsst.ts.IntegrationTests.auxtel_prepare_for_flatfield:run_auxtel_prepare_for_flatfield
    - auxtel_prepare_for_onsky = lsst.ts.IntegrationTests.auxtel_prepare_for_onsky.:un_auxtel_prepare_for_onsky
    - auxtel_shutdown = lsst.ts.IntegrationTests.auxtel_shutdown:run_auxtel_shutdown
    - auxtel_standby_disabled = lsst.ts.IntegrationTests.auxtel_standby_disabled:run_auxtel_standby_disabled
    - auxtel_stop = lsst.ts.IntegrationTests.auxtel_stop:run_auxtel_stop
    - auxtel_track_target = lsst.ts.IntegrationTests.auxtel_track_target:run_auxtel_track_target
    - auxtel_visit = lsst.ts.IntegrationTests.auxtel_visit:run_auxtel_visit
    - eas_disabled_enabled = lsst.ts.IntegrationTests.eas_disabled_enabled:run_eas_disabled_enabled
    - eas_standby_disabled = lsst.ts.IntegrationTests.eas_standby_disabled:run_eas_standby_disabled
    - enabled_offline = lsst.ts.IntegrationTests.enabled_offline:run_enabled_offline
    - maintel_disabled_enabled = lsst.ts.IntegrationTests.maintel_disabled_enabled:run_maintel_disabled_enabled
    - maintel_offline_standby = lsst.ts.IntegrationTests.maintel_offline_standby:run_maintel_offline_standby
    - maintel_standby_disabled = lsst.ts.IntegrationTests.maintel_standby_disabled:run_maintel_standby_disabled
    - obssys2_disabled_enabled = lsst.ts.IntegrationTests.obssys2_disabled_enabled:run_obssys2_disabled_enabled
    - obssys2_standby_disabled = lsst.ts.IntegrationTests.obssys2_standby_disabled:run_obssys2_standby_disabled
    - run_camera_playlist = lsst.ts.IntegrationTests.run_camera_playlist:run_camera_playlist

test:
  requires:
    - ts-conda-build =0.3
    - ts-dds
    - ts-salobj
    - ts-idl
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - yamllint

about:
  home: https://github.com/lsst-ts/ts_IntegrationTests

